# Generated by Django 4.2.5 on 2023-10-21 13:05

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='project_img/', verbose_name='Фотография')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название Видео')),
                ('description', models.TextField(verbose_name='Информация')),
                ('video_file', embed_video.fields.EmbedVideoField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
